### Registro
POST http://127.0.0.1:8000/game/registro/
Content-Type: application/json

{
    "username":"Yuu",
    "email" : "Yuu@gmail.com",
    "password" : "123456"
}

### Login
POST http://127.0.0.1:8000/game/login/
Content-Type: application/json

{
    "username": "Yuu",
    "email": "Yuu@gmail.com",
    "password": "123456"
}

### Ver biblioteca
GET http://127.0.0.1:8000/game/biblioteca/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzU2MDc0MjgsInVzZXJfaWQiOiJrTGhEcEJudHBxZnVXR0tYMUNXWDFNNnljaXEyIiwic3ViIjoia0xoRHBCbnRwcWZ1V0dLWDFDV1gxTTZ5Y2lxMiIsImlhdCI6MTc3NTYwNzQyOCwiZXhwIjoxNzc1NjExMDI4LCJlbWFpbCI6Inl1dUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsieXV1QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.PboXQRPaNjHyNDit4P1zMz_HIylXldot1sQasSIYaeT0p9ZnUAsQdtLV7AZV2Pl2W62tlZlTAM2e-zfhQ0NA_2TanrMdV3l_U-D5RRVG7yP46cJyQqvZs-XqSmZLmWv5EXYgOuZPSG2p_HvVe-cnvXXpLft3aYP-2kZpemQDOtIf7QiwZIPu6ZDFwsQCYF4y1d37vhdwHJb_mbwvxjnV0Tt2xBglimGJM4pRW6cog9c3Rwu8TuR37Wm9lVKa65oAXm7URdE5iVD5Lxc1f9fhXM2v2XLyZ8wEj-da8A4B9qe_792GlFwhtu3m_VM_XIYDXS6mt67-xM4TQ6FTb94yuQ

### Comprar 
POST http://127.0.0.1:8000/game/comprar/Mario/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzM4MzcyNDYsInVzZXJfaWQiOiJlWFh5dVhmWE9ZTXg1V0R1VEJ6N1lGcFptNXkyIiwic3ViIjoiZVhYeXVYZlhPWU14NVdEdVRCejdZRnBabTV5MiIsImlhdCI6MTc3MzgzNzI0NiwiZXhwIjoxNzczODQwODQ2LCJlbWFpbCI6ImhpZ29yQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJoaWdvckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.HGXLjGFe2gesSs-MHFvJMlvSlFIreUVw1NxicBqbe6capjKEricO9BJq0NG4Q6KHrCsP1OOc2EWM33lVbmAZLIwan-aRALwZbPNdzNkHQDoxBVAboJLjxkUigEXeCl65jU6UmjnmYD5F3oSs-CfVtP7TLd5DZijixKKSnDkivmjmFpiBZYGwJfDrXtOnrn_a3c7a2oDwwpNwhoPpCHOucEX1O3Zp2ydU5mDvlpnFq7mQmMoltI6ecZsvt2DWerjws0Kd3F7HSuMJCwHV712mHeroeMxk9IqpcRsRmHkr8NwU-tZYceA24Xc4ymhAZN1RfN3tyX7Bf8-nQERnnEk_PQ
{
    "juego_id": "Mario"
}

### Reseña
POST http://127.0.0.1:8000/game/resena/abc123/
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
    "comentario": "Excelente juego, muy entretenido",
    "calificacion": 5
}

### Registro Distribuidor
POST http://127.0.0.1:8000/game/registro-distribuidor/
Content-Type: application/json

{
    "email" : "distribuidor@gmail.com",
    "password" : "123456"
}

### Login distribuidor
POST http://127.0.0.1:8000/game/login-distribuidor/
Content-Type: application/json

{
    "email": "distribuidor@gmail.com",
    "password": "123456"
}

### Dashboard del distribuidor
GET http://127.0.0.1:8000/game/dashboard/
Authorization: Bearer 

### Listar juegos del distribuidor
GET http://127.0.0.1:8000/game/mis-juegos/
Authorization: Bearer 

### Crear un juego
POST http://127.0.0.1:8000/game/crear-juego/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Prueba",
    "descripcion": "test",
    "precio": 29.99,
    "genero": "Accion"
}

### Editar un juego
PUT http://127.0.0.1:8000/game/editar-juego/abc123/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Mario 2",
    "descripcion": "Versión mejorada",
    "precio": 19.99,
    "genero": "Plataformero"
}

### Eliminar un juego
DELETE http://127.0.0.1:8000/game/eliminar-juego/abc123/
Authorization: Bearer 

### 4 subir imagen a firestore
POST http://127.0.0.1:8000/game/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLWFkc28iLCJhdWQiOiJhcGktYWRzbyIsImF1dGhfdGltZSI6MTc3MjQ2OTIxMCwidXNlcl9pZCI6IkllTk00NUVpZ2tXUGg0QTg1RE93eUJtS29sNDIiLCJzdWIiOiJJZU5NNDVFaWdrV1BoNEE4NURPd3lCbUtvbDQyIiwiaWF0IjoxNzcyNDY5MjEwLCJleHAiOjE3NzI0NzI4MTAsImVtYWlsIjoiYXByZW5kaXozQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhcHJlbmRpejNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.X5FJSLkHx5qLMhMIVUoChyATVSgbH-VZ_veiHdWX8jc-cMfyyEnJWTUQbU6dxUC451awbgj9Ezdt5nXeWyhlKq6oPnromzjgymcYOfuTJCJ-c7mlqdo4qSlSejZTWP4QVDg4hL6iZqE0c9vzRvFKo6HGHUdZFIxk0Y5N9bzgpeqBJkHx1aQkZtl5h6XOTyVaD0j3xyn26-OOjNMKu7SIQOoWxaw7yoN0RuPbGuyoVQjCqeZ8EE-wbwEVQsljERQSbgJcUNTwPRP0WusmT-Ie_DTRgNB7UBhkL5GIo6LQyeKTu715E41zJMENdcqGPk0bbUZ3_3iyxUb9DNKjYLEB-w
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\Users\SENA\Desktop\christian2\donkey.jpeg
--MiBoundary--


### Editar juego Zelda (Prueba de WebSocket)
PUT http://127.0.0.1:8000/game/editar-juego/58WG3PlVpn6J4qIJPvxl/
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
    "titulo": "Zelda: Breath of the Wild",
    "precio": 19.99,
    "genero": "Accion",
    "descripcion": "Actualizado por WebSocket"
}


### Crear un juego (Ahora con imagen de Cloudinary)
POST http://127.0.0.1:8000/game/crear-juego/
Content-Type: application/json
Authorization: Bearer AQUI_TU_TOKEN

{
    "titulo": "Mario Kart 8",
    "descripcion": "El mejor juego de carreras.",
    "precio": 59.99,
    "genero": "Carreras",
    "imagen_url": "https://res.cloudinary.com/tu-usuario/image/upload/v1234/mariokart.jpg"
}

### ESTADISTICAS COMPRADOR
GET http://127.0.0.1:8000/game/estadisticas/comprador/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzU2MjAxMjgsInVzZXJfaWQiOiJrTGhEcEJudHBxZnVXR0tYMUNXWDFNNnljaXEyIiwic3ViIjoia0xoRHBCbnRwcWZ1V0dLWDFDV1gxTTZ5Y2lxMiIsImlhdCI6MTc3NTYyMDEyOCwiZXhwIjoxNzc1NjIzNzI4LCJlbWFpbCI6Inl1dUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsieXV1QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.A6S7tccQPiZpAeM_RtHvL-R6k8pZSytSrFqIPMX5ZbfJS2WBAIijw8BYl3fnwsGYasQ1ROr1GXUVMJx8xbDCjAzE5C553ee5LIPNhU2rwdZGoJZneWMqV4qNvDxRptak-FyW1WoRbM5Z-5l9N2A1xeqOJlywSPtPkXKN7hLB82kgBrO4WW-ZwLp6eWJZ5i5L-izgRbsHuW3A6dbo1MMRIjrvAw_44h0PnV8ATpnHxPg_Lj1nKPgFp91sZgKaTVm4yw50cnNc4MdvsL2NztDtQrL2sR695e3HC0qrhxXM8oUn0EtMmkXLysczW-tqsICbu5yNJuxGb_U4ssoD4Xuwkw
### token del comprador


### ESTADISTICAS DISTRIBUIDOR
GET http://127.0.0.1:8000/game/estadisticas/distribuidor/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzU2MjAxNzUsInVzZXJfaWQiOiJEdVYwTlhxd1lwZ1d1elE3R0N3dEQ2SUlCOTgyIiwic3ViIjoiRHVWME5YcXdZcGdXdXpRN0dDd3RENklJQjk4MiIsImlhdCI6MTc3NTYyMDE3NSwiZXhwIjoxNzc1NjIzNzc1LCJlbWFpbCI6ImRpc3RyaWJ1aWRvckBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGlzdHJpYnVpZG9yQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.0QT0ijTsPi-5jH4RfRwCNpGFPolkJhOrvVQZl7ULMQLN50T3S4OhSzp6WDSqjab53kUGb_beElFVaDr1YCcEt3eelVM5gf-rf9OTLeIv9Gr0mrUJ-TXP_GHwCO-IhtZRAZhawjUyWCuA3hARxT-7ah76V95v_Q-jgsljao5kD3XqVI_2Ch3yQRMSmRbkycuW29dmkcAHRsNAcDbEjLcz7sjecd9UrWZPkuySSPfjVEdgpknFpIa30cNU8COCLROxTcbG6aBRfAdnNyFVdoJTE0X2KJoo_V97UP7LVvs5yYlOp1rUQNWoRyDpYuzzT72Jt4TmVrxz6PuJ1FB4eh7ujQ
### token del distribuidor
