### Registro
POST http://127.0.0.1:8000/game/registro/
Content-Type: application/json

{
    "username":"Higor",
    "email" : "Higor@gmail.com",
    "password" : "123456"
}

### Login
POST http://127.0.0.1:8000/game/login/
Content-Type: application/json

{
    "username": "Higor",
    "email": "Higor@gmail.com",
    "password": "123456",
    "rol" : "comprador"
}

### Ver biblioteca
GET http://127.0.0.1:8000/game/biblioteca/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzM4MzcyNDYsInVzZXJfaWQiOiJlWFh5dVhmWE9ZTXg1V0R1VEJ6N1lGcFptNXkyIiwic3ViIjoiZVhYeXVYZlhPWU14NVdEdVRCejdZRnBabTV5MiIsImlhdCI6MTc3MzgzNzI0NiwiZXhwIjoxNzczODQwODQ2LCJlbWFpbCI6ImhpZ29yQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJoaWdvckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.HGXLjGFe2gesSs-MHFvJMlvSlFIreUVw1NxicBqbe6capjKEricO9BJq0NG4Q6KHrCsP1OOc2EWM33lVbmAZLIwan-aRALwZbPNdzNkHQDoxBVAboJLjxkUigEXeCl65jU6UmjnmYD5F3oSs-CfVtP7TLd5DZijixKKSnDkivmjmFpiBZYGwJfDrXtOnrn_a3c7a2oDwwpNwhoPpCHOucEX1O3Zp2ydU5mDvlpnFq7mQmMoltI6ecZsvt2DWerjws0Kd3F7HSuMJCwHV712mHeroeMxk9IqpcRsRmHkr8NwU-tZYceA24Xc4ymhAZN1RfN3tyX7Bf8-nQERnnEk_PQ

### Comprar 
POST http://127.0.0.1:8000/game/comprar/Mario/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYml0Y29ubmVjdC01NmJkNyIsImF1ZCI6ImJpdGNvbm5lY3QtNTZiZDciLCJhdXRoX3RpbWUiOjE3NzM4MzcyNDYsInVzZXJfaWQiOiJlWFh5dVhmWE9ZTXg1V0R1VEJ6N1lGcFptNXkyIiwic3ViIjoiZVhYeXVYZlhPWU14NVdEdVRCejdZRnBabTV5MiIsImlhdCI6MTc3MzgzNzI0NiwiZXhwIjoxNzczODQwODQ2LCJlbWFpbCI6ImhpZ29yQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJoaWdvckBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.HGXLjGFe2gesSs-MHFvJMlvSlFIreUVw1NxicBqbe6capjKEricO9BJq0NG4Q6KHrCsP1OOc2EWM33lVbmAZLIwan-aRALwZbPNdzNkHQDoxBVAboJLjxkUigEXeCl65jU6UmjnmYD5F3oSs-CfVtP7TLd5DZijixKKSnDkivmjmFpiBZYGwJfDrXtOnrn_a3c7a2oDwwpNwhoPpCHOucEX1O3Zp2ydU5mDvlpnFq7mQmMoltI6ecZsvt2DWerjws0Kd3F7HSuMJCwHV712mHeroeMxk9IqpcRsRmHkr8NwU-tZYceA24Xc4ymhAZN1RfN3tyX7Bf8-nQERnnEk_PQ
{
    "juego_id": "Mario"
}

### Reseña
POST http://127.0.0.1:8000/game/resena/abc123/
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
    "comentario": "Excelente juego, muy entretenido",
    "calificacion": 5
}

### Registro Distribuidor
POST http://127.0.0.1:8000/game/registro-distribuidor/
Content-Type: application/json

{
    "email" : "distribuidor@gmail.com",
    "password" : "123456"
}

### Login distribuidor
POST http://127.0.0.1:8000/game/login-distribuidor/
Content-Type: application/json

{
    "email": "distribuidor@gmail.com",
    "password": "123456"
}

### Dashboard del distribuidor
GET http://127.0.0.1:8000/game/dashboard/
Authorization: Bearer 

### Listar juegos del distribuidor
GET http://127.0.0.1:8000/game/mis-juegos/
Authorization: Bearer 

### Crear un juego
POST http://127.0.0.1:8000/game/crear-juego/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Zelda",
    "descripcion": "test",
    "precio": 29.99,
    "genero": "Accion"
}

### Editar un juego
PUT http://127.0.0.1:8000/game/editar-juego/abc123/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Mario 2",
    "descripcion": "Versión mejorada",
    "precio": 19.99,
    "genero": "Plataformero"
}

### Eliminar un juego
DELETE http://127.0.0.1:8000/game/eliminar-juego/abc123/
Authorization: Bearer 

### 4 subir imagen a firestore
POST http://127.0.0.1:8000/game/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLWFkc28iLCJhdWQiOiJhcGktYWRzbyIsImF1dGhfdGltZSI6MTc3MjQ2OTIxMCwidXNlcl9pZCI6IkllTk00NUVpZ2tXUGg0QTg1RE93eUJtS29sNDIiLCJzdWIiOiJJZU5NNDVFaWdrV1BoNEE4NURPd3lCbUtvbDQyIiwiaWF0IjoxNzcyNDY5MjEwLCJleHAiOjE3NzI0NzI4MTAsImVtYWlsIjoiYXByZW5kaXozQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhcHJlbmRpejNAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.X5FJSLkHx5qLMhMIVUoChyATVSgbH-VZ_veiHdWX8jc-cMfyyEnJWTUQbU6dxUC451awbgj9Ezdt5nXeWyhlKq6oPnromzjgymcYOfuTJCJ-c7mlqdo4qSlSejZTWP4QVDg4hL6iZqE0c9vzRvFKo6HGHUdZFIxk0Y5N9bzgpeqBJkHx1aQkZtl5h6XOTyVaD0j3xyn26-OOjNMKu7SIQOoWxaw7yoN0RuPbGuyoVQjCqeZ8EE-wbwEVQsljERQSbgJcUNTwPRP0WusmT-Ie_DTRgNB7UBhkL5GIo6LQyeKTu715E41zJMENdcqGPk0bbUZ3_3iyxUb9DNKjYLEB-w
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\Users\SENA\Desktop\christian2\donkey.jpeg
--MiBoundary--


### Editar juego Zelda (Prueba de WebSocket)
PUT http://127.0.0.1:8000/game/editar-juego/58WG3PlVpn6J4qIJPvxl/
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
    "titulo": "Zelda: Breath of the Wild",
    "precio": 19.99,
    "genero": "Accion",
    "descripcion": "Actualizado por WebSocket"
}